# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UXDConverter(object):
    def setupUi(self, UXDConverter):
        UXDConverter.setObjectName("UXDConverter")
        UXDConverter.resize(640, 476)
        UXDConverter.setMinimumSize(QtCore.QSize(640, 476))
        self.centralwidget = QtWidgets.QWidget(UXDConverter)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 476))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_input = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_input.setCheckable(False)
        self.pushButton_input.setFlat(False)
        self.pushButton_input.setObjectName("pushButton_input")
        self.gridLayout.addWidget(self.pushButton_input, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout.addWidget(self.lineEdit_output, 1, 1, 1, 1)
        self.pushButton_output = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_output.setObjectName("pushButton_output")
        self.gridLayout.addWidget(self.pushButton_output, 1, 2, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setDragEnabled(False)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout.addWidget(self.lineEdit_input, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.measurements = QtWidgets.QTreeWidget(self.tab)
        self.measurements.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.measurements.setRootIsDecorated(True)
        self.measurements.setColumnCount(2)
        self.measurements.setObjectName("measurements")
        self.measurements.header().setVisible(False)
        self.measurements.header().setCascadingSectionResizes(True)
        self.measurements.header().setHighlightSections(False)
        self.measurements.header().setMinimumSectionSize(100)
        self.measurements.header().setSortIndicatorShown(True)
        self.measurements.header().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.measurements, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_plot = QtWidgets.QPushButton(self.tab)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout.addWidget(self.pushButton_plot)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_wavelength = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_wavelength.setObjectName("lineEdit_wavelength")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_wavelength)
        self.lineEdit_beam_width = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_beam_width.setObjectName("lineEdit_beam_width")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_beam_width)
        self.checkBox_knifeedge = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_knifeedge.setChecked(True)
        self.checkBox_knifeedge.setObjectName("checkBox_knifeedge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_knifeedge)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_sample_length = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sample_length.setObjectName("lineEdit_sample_length")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sample_length)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.checkbox_average = QtWidgets.QCheckBox(self.groupBox)
        self.checkbox_average.setObjectName("checkbox_average")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkbox_average)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_maximum = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_maximum.setObjectName("radioButton_maximum")
        self.verticalLayout_3.addWidget(self.radioButton_maximum)
        self.radioButton_flank = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_flank.setChecked(True)
        self.radioButton_flank.setObjectName("radioButton_flank")
        self.verticalLayout_3.addWidget(self.radioButton_flank)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_manual = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.horizontalLayout_3.addWidget(self.radioButton_manual)
        self.lineEdit_normalization_factor = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_normalization_factor.setObjectName("lineEdit_normalization_factor")
        self.horizontalLayout_3.addWidget(self.lineEdit_normalization_factor)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.pushbutton_select_graph = QtWidgets.QPushButton(self.groupBox_2)
        self.pushbutton_select_graph.setObjectName("pushbutton_select_graph")
        self.verticalLayout_4.addWidget(self.pushbutton_select_graph)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.horizontalLayout_2.addWidget(self.pushButton_convert)
        self.checkBox_view_plot = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_view_plot.setChecked(True)
        self.checkBox_view_plot.setObjectName("checkBox_view_plot")
        self.horizontalLayout_2.addWidget(self.checkBox_view_plot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        UXDConverter.setCentralWidget(self.centralwidget)

        self.retranslateUi(UXDConverter)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UXDConverter)

    def retranslateUi(self, UXDConverter):
        _translate = QtCore.QCoreApplication.translate
        UXDConverter.setWindowTitle(_translate("UXDConverter", "UXDConverter"))
        self.label_2.setText(_translate("UXDConverter", "Output file"))
        self.pushButton_input.setText(_translate("UXDConverter", "Browse"))
        self.label.setText(_translate("UXDConverter", "Input file"))
        self.pushButton_output.setText(_translate("UXDConverter", "Browse"))
        self.measurements.headerItem().setText(0, _translate("UXDConverter", "asd"))
        self.measurements.headerItem().setText(1, _translate("UXDConverter", "2"))
        self.pushButton_plot.setToolTip(_translate("UXDConverter", "Plot the selected measurements in a theta-intensity graph"))
        self.pushButton_plot.setText(_translate("UXDConverter", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UXDConverter", "Measurement"))
        self.groupBox.setTitle(_translate("UXDConverter", "Measurement Context"))
        self.label_4.setText(_translate("UXDConverter", "X-Ray wavelength [A]"))
        self.label_5.setText(_translate("UXDConverter", "X-Ray beam width [mm]"))
        self.label_6.setText(_translate("UXDConverter", "Knife Edge"))
        self.lineEdit_wavelength.setText(_translate("UXDConverter", "1,5418"))
        self.lineEdit_beam_width.setText(_translate("UXDConverter", "0,1"))
        self.checkBox_knifeedge.setToolTip(_translate("UXDConverter", "Was the measurement carried out with a knife edge?"))
        self.checkBox_knifeedge.setText(_translate("UXDConverter", "Enabled"))
        self.label_3.setText(_translate("UXDConverter", "Sample length [mm]"))
        self.lineEdit_sample_length.setText(_translate("UXDConverter", "10,0"))
        self.label_7.setText(_translate("UXDConverter", "Average overlapping data"))
        self.checkbox_average.setToolTip(_translate("UXDConverter", "Average data on overlapping regions"))
        self.checkbox_average.setText(_translate("UXDConverter", "Enabled"))
        self.groupBox_2.setTitle(_translate("UXDConverter", "Normalization"))
        self.radioButton_maximum.setToolTip(_translate("UXDConverter", "Normalize the maximal counts per second to 1"))
        self.radioButton_maximum.setText(_translate("UXDConverter", "maximum"))
        self.radioButton_flank.setToolTip(_translate("UXDConverter", "Normalize the point with the lowest absolute slope to one. Only points left to the first flank are considered"))
        self.radioButton_flank.setText(_translate("UXDConverter", "first flank and derivative"))
        self.radioButton_manual.setToolTip(_translate("UXDConverter", "Normalize all points using the given scaling factor"))
        self.radioButton_manual.setText(_translate("UXDConverter", "manual"))
        self.lineEdit_normalization_factor.setText(_translate("UXDConverter", "1,0"))
        self.pushbutton_select_graph.setToolTip(_translate("UXDConverter", "Select a scaling factor from graph. Click on graph and press \'x\' button or double click"))
        self.pushbutton_select_graph.setText(_translate("UXDConverter", "Select from graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UXDConverter", "Settings"))
        self.pushButton_convert.setToolTip(_translate("UXDConverter", "Convert the measurements and save into output file"))
        self.pushButton_convert.setText(_translate("UXDConverter", "Convert"))
        self.checkBox_view_plot.setText(_translate("UXDConverter", "Plot after Conversion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UXDConverter = QtWidgets.QMainWindow()
    ui = Ui_UXDConverter()
    ui.setupUi(UXDConverter)
    UXDConverter.show()
    sys.exit(app.exec_())

